// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.3
// source: node_attribute.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeAttributeType int32

const (
	NodeAttributeType_EXECUTOR NodeAttributeType = 0
	NodeAttributeType_MANAGER  NodeAttributeType = 1
	NodeAttributeType_LOGGING  NodeAttributeType = 2
	NodeAttributeType_API      NodeAttributeType = 3
)

// Enum value maps for NodeAttributeType.
var (
	NodeAttributeType_name = map[int32]string{
		0: "EXECUTOR",
		1: "MANAGER",
		2: "LOGGING",
		3: "API",
	}
	NodeAttributeType_value = map[string]int32{
		"EXECUTOR": 0,
		"MANAGER":  1,
		"LOGGING":  2,
		"API":      3,
	}
)

func (x NodeAttributeType) Enum() *NodeAttributeType {
	p := new(NodeAttributeType)
	*p = x
	return p
}

func (x NodeAttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeAttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_node_attribute_proto_enumTypes[0].Descriptor()
}

func (NodeAttributeType) Type() protoreflect.EnumType {
	return &file_node_attribute_proto_enumTypes[0]
}

func (x NodeAttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeAttributeType.Descriptor instead.
func (NodeAttributeType) EnumDescriptor() ([]byte, []int) {
	return file_node_attribute_proto_rawDescGZIP(), []int{0}
}

type NodeAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	Attribute     []NodeAttributeType    `protobuf:"varint,2,rep,packed,name=attribute,proto3,enum=msg.NodeAttributeType" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAttribute) Reset() {
	*x = NodeAttribute{}
	mi := &file_node_attribute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAttribute) ProtoMessage() {}

func (x *NodeAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_node_attribute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAttribute.ProtoReflect.Descriptor instead.
func (*NodeAttribute) Descriptor() ([]byte, []int) {
	return file_node_attribute_proto_rawDescGZIP(), []int{0}
}

func (x *NodeAttribute) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeAttribute) GetAttribute() []NodeAttributeType {
	if x != nil {
		return x.Attribute
	}
	return nil
}

var File_node_attribute_proto protoreflect.FileDescriptor

var file_node_attribute_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x61, 0x0a, 0x0d, 0x4e,
	0x6f, 0x64, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2a, 0x44,
	0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x4f, 0x52, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x4c, 0x4f, 0x47, 0x47, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x41,
	0x50, 0x49, 0x10, 0x03, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x64, 0x74, 0x6f, 0x74, 0x6f, 0x77, 0x2f, 0x69, 0x61, 0x63, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x3b, 0x6d, 0x73, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_node_attribute_proto_rawDescOnce sync.Once
	file_node_attribute_proto_rawDescData []byte
)

func file_node_attribute_proto_rawDescGZIP() []byte {
	file_node_attribute_proto_rawDescOnce.Do(func() {
		file_node_attribute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_node_attribute_proto_rawDesc), len(file_node_attribute_proto_rawDesc)))
	})
	return file_node_attribute_proto_rawDescData
}

var file_node_attribute_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_node_attribute_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_attribute_proto_goTypes = []any{
	(NodeAttributeType)(0), // 0: msg.NodeAttributeType
	(*NodeAttribute)(nil),  // 1: msg.NodeAttribute
}
var file_node_attribute_proto_depIdxs = []int32{
	0, // 0: msg.NodeAttribute.attribute:type_name -> msg.NodeAttributeType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_node_attribute_proto_init() }
func file_node_attribute_proto_init() {
	if File_node_attribute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_node_attribute_proto_rawDesc), len(file_node_attribute_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_attribute_proto_goTypes,
		DependencyIndexes: file_node_attribute_proto_depIdxs,
		EnumInfos:         file_node_attribute_proto_enumTypes,
		MessageInfos:      file_node_attribute_proto_msgTypes,
	}.Build()
	File_node_attribute_proto = out.File
	file_node_attribute_proto_goTypes = nil
	file_node_attribute_proto_depIdxs = nil
}
